// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellSelector) DeepCopyInto(out *CellSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellSelector.
func (in *CellSelector) DeepCopy() *CellSelector {
	if in == nil {
		return nil
	}
	out := new(CellSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Etcd2Lockserver) DeepCopyInto(out *Etcd2Lockserver) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Etcd2Lockserver.
func (in *Etcd2Lockserver) DeepCopy() *Etcd2Lockserver {
	if in == nil {
		return nil
	}
	out := new(Etcd2Lockserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRange) DeepCopyInto(out *KeyRange) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRange.
func (in *KeyRange) DeepCopy() *KeyRange {
	if in == nil {
		return nil
	}
	out := new(KeyRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLContainer) DeepCopyInto(out *MySQLContainer) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLContainer.
func (in *MySQLContainer) DeepCopy() *MySQLContainer {
	if in == nil {
		return nil
	}
	out := new(MySQLContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletContainers) DeepCopyInto(out *TabletContainers) {
	*out = *in
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLContainer)
		(*in).DeepCopyInto(*out)
	}
	if in.VTTablet != nil {
		in, out := &in.VTTablet, &out.VTTablet
		*out = new(VTTabletContainer)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletContainers.
func (in *TabletContainers) DeepCopy() *TabletContainers {
	if in == nil {
		return nil
	}
	out := new(TabletContainers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletCredentials) DeepCopyInto(out *TabletCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletCredentials.
func (in *TabletCredentials) DeepCopy() *TabletCredentials {
	if in == nil {
		return nil
	}
	out := new(TabletCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletDatastore) DeepCopyInto(out *TabletDatastore) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletDatastore.
func (in *TabletDatastore) DeepCopy() *TabletDatastore {
	if in == nil {
		return nil
	}
	out := new(TabletDatastore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTComponent) DeepCopyInto(out *VTComponent) {
	*out = *in
	if in.ContainerSpec != nil {
		in, out := &in.ContainerSpec, &out.ContainerSpec
		*out = make([]*v1.Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTComponent.
func (in *VTComponent) DeepCopy() *VTComponent {
	if in == nil {
		return nil
	}
	out := new(VTComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTGate) DeepCopyInto(out *VTGate) {
	*out = *in
	in.VTComponent.DeepCopyInto(&out.VTComponent)
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CellSelector != nil {
		in, out := &in.CellSelector, &out.CellSelector
		*out = new(CellSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTGate.
func (in *VTGate) DeepCopy() *VTGate {
	if in == nil {
		return nil
	}
	out := new(VTGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTGateCredentials) DeepCopyInto(out *VTGateCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTGateCredentials.
func (in *VTGateCredentials) DeepCopy() *VTGateCredentials {
	if in == nil {
		return nil
	}
	out := new(VTGateCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTTabletContainer) DeepCopyInto(out *VTTabletContainer) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTTabletContainer.
func (in *VTTabletContainer) DeepCopy() *VTTabletContainer {
	if in == nil {
		return nil
	}
	out := new(VTTabletContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessBatchOptions) DeepCopyInto(out *VitessBatchOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessBatchOptions.
func (in *VitessBatchOptions) DeepCopy() *VitessBatchOptions {
	if in == nil {
		return nil
	}
	out := new(VitessBatchOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCell) DeepCopyInto(out *VitessCell) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCell.
func (in *VitessCell) DeepCopy() *VitessCell {
	if in == nil {
		return nil
	}
	out := new(VitessCell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCell) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellDefaults) DeepCopyInto(out *VitessCellDefaults) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellDefaults.
func (in *VitessCellDefaults) DeepCopy() *VitessCellDefaults {
	if in == nil {
		return nil
	}
	out := new(VitessCellDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellList) DeepCopyInto(out *VitessCellList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessCell, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellList.
func (in *VitessCellList) DeepCopy() *VitessCellList {
	if in == nil {
		return nil
	}
	out := new(VitessCellList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCellList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellMySQLProtocol) DeepCopyInto(out *VitessCellMySQLProtocol) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellMySQLProtocol.
func (in *VitessCellMySQLProtocol) DeepCopy() *VitessCellMySQLProtocol {
	if in == nil {
		return nil
	}
	out := new(VitessCellMySQLProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellParents) DeepCopyInto(out *VitessCellParents) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(VitessCluster)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellParents.
func (in *VitessCellParents) DeepCopy() *VitessCellParents {
	if in == nil {
		return nil
	}
	out := new(VitessCellParents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellSpec) DeepCopyInto(out *VitessCellSpec) {
	*out = *in
	if in.Lockserver != nil {
		in, out := &in.Lockserver, &out.Lockserver
		*out = new(VitessLockserver)
		(*in).DeepCopyInto(*out)
	}
	if in.LockserverRef != nil {
		in, out := &in.LockserverRef, &out.LockserverRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(VitessCellDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQLProtocol != nil {
		in, out := &in.MySQLProtocol, &out.MySQLProtocol
		*out = new(VitessCellMySQLProtocol)
		(*in).DeepCopyInto(*out)
	}
	if in.VTGate != nil {
		in, out := &in.VTGate, &out.VTGate
		*out = make([]VTComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VTWorker != nil {
		in, out := &in.VTWorker, &out.VTWorker
		*out = make([]VTComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VTCtld != nil {
		in, out := &in.VTCtld, &out.VTCtld
		*out = make([]VTComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Orchestrator != nil {
		in, out := &in.Orchestrator, &out.Orchestrator
		*out = make([]VTComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.parent.DeepCopyInto(&out.parent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellSpec.
func (in *VitessCellSpec) DeepCopy() *VitessCellSpec {
	if in == nil {
		return nil
	}
	out := new(VitessCellSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCluster) DeepCopyInto(out *VitessCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCluster.
func (in *VitessCluster) DeepCopy() *VitessCluster {
	if in == nil {
		return nil
	}
	out := new(VitessCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterCondition) DeepCopyInto(out *VitessClusterCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterCondition.
func (in *VitessClusterCondition) DeepCopy() *VitessClusterCondition {
	if in == nil {
		return nil
	}
	out := new(VitessClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterList) DeepCopyInto(out *VitessClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterList.
func (in *VitessClusterList) DeepCopy() *VitessClusterList {
	if in == nil {
		return nil
	}
	out := new(VitessClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterSpec) DeepCopyInto(out *VitessClusterSpec) {
	*out = *in
	if in.Lockserver != nil {
		in, out := &in.Lockserver, &out.Lockserver
		*out = new(VitessLockserver)
		(*in).DeepCopyInto(*out)
	}
	if in.LockserverRef != nil {
		in, out := &in.LockserverRef, &out.LockserverRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]*VitessCell, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VitessCell)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CellSelector != nil {
		in, out := &in.CellSelector, &out.CellSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Keyspaces != nil {
		in, out := &in.Keyspaces, &out.Keyspaces
		*out = make([]*VitessKeyspace, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VitessKeyspace)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.KeyspaceSelector != nil {
		in, out := &in.KeyspaceSelector, &out.KeyspaceSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterSpec.
func (in *VitessClusterSpec) DeepCopy() *VitessClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VitessClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterStatus) DeepCopyInto(out *VitessClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]VitessClusterCondition, len(*in))
		copy(*out, *in)
	}
	if in.Lockserver != nil {
		in, out := &in.Lockserver, &out.Lockserver
		*out = new(VitessLockserverStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterStatus.
func (in *VitessClusterStatus) DeepCopy() *VitessClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VitessClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspace) DeepCopyInto(out *VitessKeyspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspace.
func (in *VitessKeyspace) DeepCopy() *VitessKeyspace {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessKeyspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspaceList) DeepCopyInto(out *VitessKeyspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessKeyspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspaceList.
func (in *VitessKeyspaceList) DeepCopy() *VitessKeyspaceList {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessKeyspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspaceParents) DeepCopyInto(out *VitessKeyspaceParents) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(VitessCluster)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspaceParents.
func (in *VitessKeyspaceParents) DeepCopy() *VitessKeyspaceParents {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspaceParents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspaceSpec) DeepCopyInto(out *VitessKeyspaceSpec) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(VitessShardOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]*VitessShard, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VitessShard)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ShardSelector != nil {
		in, out := &in.ShardSelector, &out.ShardSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.parent.DeepCopyInto(&out.parent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspaceSpec.
func (in *VitessKeyspaceSpec) DeepCopy() *VitessKeyspaceSpec {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserver) DeepCopyInto(out *VitessLockserver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserver.
func (in *VitessLockserver) DeepCopy() *VitessLockserver {
	if in == nil {
		return nil
	}
	out := new(VitessLockserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessLockserver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserverList) DeepCopyInto(out *VitessLockserverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessLockserver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserverList.
func (in *VitessLockserverList) DeepCopy() *VitessLockserverList {
	if in == nil {
		return nil
	}
	out := new(VitessLockserverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessLockserverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserverSpec) DeepCopyInto(out *VitessLockserverSpec) {
	*out = *in
	if in.Etcd2 != nil {
		in, out := &in.Etcd2, &out.Etcd2
		*out = new(Etcd2Lockserver)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserverSpec.
func (in *VitessLockserverSpec) DeepCopy() *VitessLockserverSpec {
	if in == nil {
		return nil
	}
	out := new(VitessLockserverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserverStatus) DeepCopyInto(out *VitessLockserverStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserverStatus.
func (in *VitessLockserverStatus) DeepCopy() *VitessLockserverStatus {
	if in == nil {
		return nil
	}
	out := new(VitessLockserverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShard) DeepCopyInto(out *VitessShard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShard.
func (in *VitessShard) DeepCopy() *VitessShard {
	if in == nil {
		return nil
	}
	out := new(VitessShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessShard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardList) DeepCopyInto(out *VitessShardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardList.
func (in *VitessShardList) DeepCopy() *VitessShardList {
	if in == nil {
		return nil
	}
	out := new(VitessShardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessShardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardOptions) DeepCopyInto(out *VitessShardOptions) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Batch = in.Batch
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(TabletContainers)
		(*in).DeepCopyInto(*out)
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CellSelector != nil {
		in, out := &in.CellSelector, &out.CellSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardOptions.
func (in *VitessShardOptions) DeepCopy() *VitessShardOptions {
	if in == nil {
		return nil
	}
	out := new(VitessShardOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardParents) DeepCopyInto(out *VitessShardParents) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(VitessCluster)
		(*in).DeepCopyInto(*out)
	}
	if in.Keyspace != nil {
		in, out := &in.Keyspace, &out.Keyspace
		*out = new(VitessKeyspace)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardParents.
func (in *VitessShardParents) DeepCopy() *VitessShardParents {
	if in == nil {
		return nil
	}
	out := new(VitessShardParents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardSpec) DeepCopyInto(out *VitessShardSpec) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(VitessShardOptions)
		(*in).DeepCopyInto(*out)
	}
	out.KeyRange = in.KeyRange
	if in.Tablets != nil {
		in, out := &in.Tablets, &out.Tablets
		*out = make([]*VitessTablet, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VitessTablet)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TabletSelector != nil {
		in, out := &in.TabletSelector, &out.TabletSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.parent.DeepCopyInto(&out.parent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardSpec.
func (in *VitessShardSpec) DeepCopy() *VitessShardSpec {
	if in == nil {
		return nil
	}
	out := new(VitessShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTablet) DeepCopyInto(out *VitessTablet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTablet.
func (in *VitessTablet) DeepCopy() *VitessTablet {
	if in == nil {
		return nil
	}
	out := new(VitessTablet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessTablet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTabletList) DeepCopyInto(out *VitessTabletList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessTablet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTabletList.
func (in *VitessTabletList) DeepCopy() *VitessTabletList {
	if in == nil {
		return nil
	}
	out := new(VitessTabletList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessTabletList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTabletParents) DeepCopyInto(out *VitessTabletParents) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(VitessCluster)
		(*in).DeepCopyInto(*out)
	}
	if in.Cell != nil {
		in, out := &in.Cell, &out.Cell
		*out = new(VitessCell)
		(*in).DeepCopyInto(*out)
	}
	if in.Keyspace != nil {
		in, out := &in.Keyspace, &out.Keyspace
		*out = new(VitessKeyspace)
		(*in).DeepCopyInto(*out)
	}
	if in.Shard != nil {
		in, out := &in.Shard, &out.Shard
		*out = new(VitessShard)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTabletParents.
func (in *VitessTabletParents) DeepCopy() *VitessTabletParents {
	if in == nil {
		return nil
	}
	out := new(VitessTabletParents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTabletSpec) DeepCopyInto(out *VitessTabletSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Datastore = in.Datastore
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(TabletContainers)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeClaim != nil {
		in, out := &in.VolumeClaim, &out.VolumeClaim
		*out = new(v1.PersistentVolumeClaimVolumeSource)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(TabletCredentials)
		(*in).DeepCopyInto(*out)
	}
	in.parent.DeepCopyInto(&out.parent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTabletSpec.
func (in *VitessTabletSpec) DeepCopy() *VitessTabletSpec {
	if in == nil {
		return nil
	}
	out := new(VitessTabletSpec)
	in.DeepCopyInto(out)
	return out
}
